export enum apiManagerConstants {
  INIT = "INIT",
  FILTER_TREE = "FILTER_TREE",
  // 新增项目
  ADD_PROJECT = "ADD_PROJECT",
  // 打开项目，查看
  OPEN_PROJECT = "OPEN_PROJECT",
  //
  UPDATE_PROJECT = "UPDATE_PROJECT",
  // 删除项目
  DELETE_PROJECT = "DELETE_PROJECT",

  // 从根打开，归属根
  OPEN_NEW_REQUEST_ROOT = "OPEN_NEW_REQUEST_ROOT",
  // 从目录打开，归属该目录
  // 从API打开，保存时归属该API父类，保持同级
  OPEN_NEW_REQUEST_TREE = "OPEN_NEW_REQUEST_TREE",

  OPEN_EXIST_REQUEST = "OPEN_EXIST_REQUEST",
  // 更新接口，保存到树中
  UPDATE_NEW_REQUEST = "UPDATE_NEW_REQUEST",
  UPDATE_EXIST_REQUEST = "UPDATE_EXIST_REQUEST",
  // 删除接口
  DELETE_REQUEST = "DELETE_REQUEST",
  CHANGE_ACTIVE_INDEX = "CHANGE_ACTIVE_INDEX",
  REMOVE_PANEL_BY_KEY = "REMOVE_PANEL_BY_KEY",
}
